// AUTO-GENERATED by scripts/fetch-flickr.mjs — do not edit by hand.
// Source: https://www.flickr.com/photos/eyeinstudio/albums/

export type PortfolioPhoto = { id: string; src: string; width: number; height: number };

export type PortfolioAlbum = {
  id: string;
  title: string;
  slug: string;
  description: string;
  cover: string;
  photos: PortfolioPhoto[];
};

export const albums: PortfolioAlbum[] = [
  {
    "id": "72177720332566812",
    "title": "MOVE UP GLOBAL 2025",
    "slug": "move-up-global-2025",
    "description": "World Neglected Tropical Diseases & Leprosy Day — “Unite, Act, Eliminate”.",
    "cover": "/portfolio/move-up-global-2025/55151937251.jpg",
    "photos": [
      {
        "id": "55151937251",
        "src": "/portfolio/move-up-global-2025/55151937251.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151040532",
        "src": "/portfolio/move-up-global-2025/55151040532.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151043672",
        "src": "/portfolio/move-up-global-2025/55151043672.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151043597",
        "src": "/portfolio/move-up-global-2025/55151043597.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152313505",
        "src": "/portfolio/move-up-global-2025/55152313505.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152313490",
        "src": "/portfolio/move-up-global-2025/55152313490.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151043517",
        "src": "/portfolio/move-up-global-2025/55151043517.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152097553",
        "src": "/portfolio/move-up-global-2025/55152097553.jpg",
        "width": 1600,
        "height": 1065
      },
      {
        "id": "55151040977",
        "src": "/portfolio/move-up-global-2025/55151040977.jpg",
        "width": 1600,
        "height": 1065
      },
      {
        "id": "55152311030",
        "src": "/portfolio/move-up-global-2025/55152311030.jpg",
        "width": 1600,
        "height": 1065
      },
      {
        "id": "55151935311",
        "src": "/portfolio/move-up-global-2025/55151935311.jpg",
        "width": 1023,
        "height": 681
      },
      {
        "id": "55152311375",
        "src": "/portfolio/move-up-global-2025/55152311375.jpg",
        "width": 681,
        "height": 1023
      },
      {
        "id": "55151937236",
        "src": "/portfolio/move-up-global-2025/55151937236.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151043377",
        "src": "/portfolio/move-up-global-2025/55151043377.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152170319",
        "src": "/portfolio/move-up-global-2025/55152170319.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152170269",
        "src": "/portfolio/move-up-global-2025/55152170269.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152313260",
        "src": "/portfolio/move-up-global-2025/55152313260.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151043297",
        "src": "/portfolio/move-up-global-2025/55151043297.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152100153",
        "src": "/portfolio/move-up-global-2025/55152100153.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152100103",
        "src": "/portfolio/move-up-global-2025/55152100103.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152313065",
        "src": "/portfolio/move-up-global-2025/55152313065.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151043087",
        "src": "/portfolio/move-up-global-2025/55151043087.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152313020",
        "src": "/portfolio/move-up-global-2025/55152313020.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152312945",
        "src": "/portfolio/move-up-global-2025/55152312945.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151042887",
        "src": "/portfolio/move-up-global-2025/55151042887.jpg",
        "width": 819,
        "height": 1024
      }
    ]
  },
  {
    "id": "72177720332559645",
    "title": "FOREVER SUCCESS DAY 2026",
    "slug": "forever-success-day-2026",
    "description": "Annual recognition day celebrating partners and achievements.",
    "cover": "/portfolio/forever-success-day-2026/55150920597.jpg",
    "photos": [
      {
        "id": "55150920597",
        "src": "/portfolio/forever-success-day-2026/55150920597.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152190215",
        "src": "/portfolio/forever-success-day-2026/55152190215.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151814026",
        "src": "/portfolio/forever-success-day-2026/55151814026.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151975778",
        "src": "/portfolio/forever-success-day-2026/55151975778.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151975803",
        "src": "/portfolio/forever-success-day-2026/55151975803.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150921707",
        "src": "/portfolio/forever-success-day-2026/55150921707.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151818926",
        "src": "/portfolio/forever-success-day-2026/55151818926.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151818786",
        "src": "/portfolio/forever-success-day-2026/55151818786.jpg",
        "width": 1024,
        "height": 745
      },
      {
        "id": "55151818661",
        "src": "/portfolio/forever-success-day-2026/55151818661.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152195075",
        "src": "/portfolio/forever-success-day-2026/55152195075.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152051159",
        "src": "/portfolio/forever-success-day-2026/55152051159.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151818316",
        "src": "/portfolio/forever-success-day-2026/55151818316.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152194815",
        "src": "/portfolio/forever-success-day-2026/55152194815.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150924447",
        "src": "/portfolio/forever-success-day-2026/55150924447.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150924592",
        "src": "/portfolio/forever-success-day-2026/55150924592.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151817881",
        "src": "/portfolio/forever-success-day-2026/55151817881.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152190530",
        "src": "/portfolio/forever-success-day-2026/55152190530.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152190345",
        "src": "/portfolio/forever-success-day-2026/55152190345.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150920142",
        "src": "/portfolio/forever-success-day-2026/55150920142.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151814386",
        "src": "/portfolio/forever-success-day-2026/55151814386.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151976353",
        "src": "/portfolio/forever-success-day-2026/55151976353.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150920452",
        "src": "/portfolio/forever-success-day-2026/55150920452.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55152191125",
        "src": "/portfolio/forever-success-day-2026/55152191125.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151980173",
        "src": "/portfolio/forever-success-day-2026/55151980173.jpg",
        "width": 1600,
        "height": 1066
      }
    ]
  },
  {
    "id": "72177720332581883",
    "title": "FOREVER TRAININGS",
    "slug": "forever-trainings",
    "description": "Skill-building sessions and team enablement workshops.",
    "cover": "/portfolio/forever-trainings/55151799046.jpg",
    "photos": [
      {
        "id": "55151799046",
        "src": "/portfolio/forever-trainings/55151799046.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150909217",
        "src": "/portfolio/forever-trainings/55150909217.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150901542",
        "src": "/portfolio/forever-trainings/55150901542.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151795451",
        "src": "/portfolio/forever-trainings/55151795451.jpg",
        "width": 1600,
        "height": 1164
      },
      {
        "id": "55151957028",
        "src": "/portfolio/forever-trainings/55151957028.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152028244",
        "src": "/portfolio/forever-trainings/55152028244.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151957683",
        "src": "/portfolio/forever-trainings/55151957683.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55152028394",
        "src": "/portfolio/forever-trainings/55152028394.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152171930",
        "src": "/portfolio/forever-trainings/55152171930.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150902672",
        "src": "/portfolio/forever-trainings/55150902672.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151796356",
        "src": "/portfolio/forever-trainings/55151796356.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151958103",
        "src": "/portfolio/forever-trainings/55151958103.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151958008",
        "src": "/portfolio/forever-trainings/55151958008.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152029329",
        "src": "/portfolio/forever-trainings/55152029329.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152029279",
        "src": "/portfolio/forever-trainings/55152029279.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151958158",
        "src": "/portfolio/forever-trainings/55151958158.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152172590",
        "src": "/portfolio/forever-trainings/55152172590.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152029629",
        "src": "/portfolio/forever-trainings/55152029629.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150903682",
        "src": "/portfolio/forever-trainings/55150903682.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152172995",
        "src": "/portfolio/forever-trainings/55152172995.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55152173090",
        "src": "/portfolio/forever-trainings/55152173090.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151797636",
        "src": "/portfolio/forever-trainings/55151797636.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55152173480",
        "src": "/portfolio/forever-trainings/55152173480.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151959348",
        "src": "/portfolio/forever-trainings/55151959348.jpg",
        "width": 1024,
        "height": 819
      },
      {
        "id": "55152173465",
        "src": "/portfolio/forever-trainings/55152173465.jpg",
        "width": 819,
        "height": 1024
      }
    ]
  },
  {
    "id": "72177720332581543",
    "title": "COMMON WEALTH DAY 2026",
    "slug": "common-wealth-day-2026",
    "description": "Commonwealth Day commemoration in Kigali.",
    "cover": "/portfolio/common-wealth-day-2026/55151993144.jpg",
    "photos": [
      {
        "id": "55151993144",
        "src": "/portfolio/common-wealth-day-2026/55151993144.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150865682",
        "src": "/portfolio/common-wealth-day-2026/55150865682.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152135180",
        "src": "/portfolio/common-wealth-day-2026/55152135180.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151921538",
        "src": "/portfolio/common-wealth-day-2026/55151921538.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151921533",
        "src": "/portfolio/common-wealth-day-2026/55151921533.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152135315",
        "src": "/portfolio/common-wealth-day-2026/55152135315.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150865842",
        "src": "/portfolio/common-wealth-day-2026/55150865842.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152135345",
        "src": "/portfolio/common-wealth-day-2026/55152135345.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151921723",
        "src": "/portfolio/common-wealth-day-2026/55151921723.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150865962",
        "src": "/portfolio/common-wealth-day-2026/55150865962.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151759991",
        "src": "/portfolio/common-wealth-day-2026/55151759991.jpg",
        "width": 1600,
        "height": 1164
      },
      {
        "id": "55151759976",
        "src": "/portfolio/common-wealth-day-2026/55151759976.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151921848",
        "src": "/portfolio/common-wealth-day-2026/55151921848.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152135605",
        "src": "/portfolio/common-wealth-day-2026/55152135605.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150866082",
        "src": "/portfolio/common-wealth-day-2026/55150866082.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152135600",
        "src": "/portfolio/common-wealth-day-2026/55152135600.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151760131",
        "src": "/portfolio/common-wealth-day-2026/55151760131.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150866217",
        "src": "/portfolio/common-wealth-day-2026/55150866217.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150866267",
        "src": "/portfolio/common-wealth-day-2026/55150866267.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151760196",
        "src": "/portfolio/common-wealth-day-2026/55151760196.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55152135845",
        "src": "/portfolio/common-wealth-day-2026/55152135845.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151922208",
        "src": "/portfolio/common-wealth-day-2026/55151922208.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151760261",
        "src": "/portfolio/common-wealth-day-2026/55151760261.jpg",
        "width": 1600,
        "height": 1066
      }
    ]
  },
  {
    "id": "72177720332558780",
    "title": "CENTER FOR DEVELOPMENT POLICY Feb 2026",
    "slug": "center-for-development-policy-feb-2026",
    "description": "Policy convening and panel discussions.",
    "cover": "/portfolio/center-for-development-policy-feb-2026/55152117310.jpg",
    "photos": [
      {
        "id": "55152117310",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152117310.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55150847927",
        "src": "/portfolio/center-for-development-policy-feb-2026/55150847927.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151974729",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151974729.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151741946",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151741946.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151741966",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151741966.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151742106",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151742106.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152117365",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152117365.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151975054",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975054.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151742126",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151742126.jpg",
        "width": 1600,
        "height": 960
      },
      {
        "id": "55150848417",
        "src": "/portfolio/center-for-development-policy-feb-2026/55150848417.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152117705",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152117705.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151742486",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151742486.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151903883",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151903883.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150848477",
        "src": "/portfolio/center-for-development-policy-feb-2026/55150848477.jpg",
        "width": 1600,
        "height": 960
      },
      {
        "id": "55151975254",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975254.jpg",
        "width": 1600,
        "height": 960
      },
      {
        "id": "55151975694",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975694.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151975364",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975364.jpg",
        "width": 1600,
        "height": 873
      },
      {
        "id": "55152118350",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152118350.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151975554",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975554.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152118220",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152118220.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151975654",
        "src": "/portfolio/center-for-development-policy-feb-2026/55151975654.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55150848917",
        "src": "/portfolio/center-for-development-policy-feb-2026/55150848917.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55152118395",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152118395.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55152118435",
        "src": "/portfolio/center-for-development-policy-feb-2026/55152118435.jpg",
        "width": 1024,
        "height": 683
      }
    ]
  },
  {
    "id": "72177720332592539",
    "title": "AZAM DINNER Feb 2025",
    "slug": "azam-dinner-feb-2025",
    "description": "Corporate dinner and partner appreciation evening.",
    "cover": "/portfolio/azam-dinner-feb-2025/55151955269.jpg",
    "photos": [
      {
        "id": "55151955269",
        "src": "/portfolio/azam-dinner-feb-2025/55151955269.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151721056",
        "src": "/portfolio/azam-dinner-feb-2025/55151721056.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151721041",
        "src": "/portfolio/azam-dinner-feb-2025/55151721041.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152096960",
        "src": "/portfolio/azam-dinner-feb-2025/55152096960.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151721016",
        "src": "/portfolio/azam-dinner-feb-2025/55151721016.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151721196",
        "src": "/portfolio/azam-dinner-feb-2025/55151721196.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151882483",
        "src": "/portfolio/azam-dinner-feb-2025/55151882483.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151721221",
        "src": "/portfolio/azam-dinner-feb-2025/55151721221.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151721201",
        "src": "/portfolio/azam-dinner-feb-2025/55151721201.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55151954259",
        "src": "/portfolio/azam-dinner-feb-2025/55151954259.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152097305",
        "src": "/portfolio/azam-dinner-feb-2025/55152097305.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55150827627",
        "src": "/portfolio/azam-dinner-feb-2025/55150827627.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151721376",
        "src": "/portfolio/azam-dinner-feb-2025/55151721376.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55151954439",
        "src": "/portfolio/azam-dinner-feb-2025/55151954439.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55150827712",
        "src": "/portfolio/azam-dinner-feb-2025/55150827712.jpg",
        "width": 745,
        "height": 1024
      },
      {
        "id": "55152097630",
        "src": "/portfolio/azam-dinner-feb-2025/55152097630.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151882848",
        "src": "/portfolio/azam-dinner-feb-2025/55151882848.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151882958",
        "src": "/portfolio/azam-dinner-feb-2025/55151882958.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152097790",
        "src": "/portfolio/azam-dinner-feb-2025/55152097790.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150828112",
        "src": "/portfolio/azam-dinner-feb-2025/55150828112.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151954819",
        "src": "/portfolio/azam-dinner-feb-2025/55151954819.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150828192",
        "src": "/portfolio/azam-dinner-feb-2025/55150828192.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150841172",
        "src": "/portfolio/azam-dinner-feb-2025/55150841172.jpg",
        "width": 1600,
        "height": 800
      },
      {
        "id": "55152098005",
        "src": "/portfolio/azam-dinner-feb-2025/55152098005.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151967739",
        "src": "/portfolio/azam-dinner-feb-2025/55151967739.jpg",
        "width": 1600,
        "height": 800
      }
    ]
  },
  {
    "id": "72177720332581048",
    "title": "AZAM'S STAFF HOUSING PROJECT 2025",
    "slug": "azam-s-staff-housing-project-2025",
    "description": "Project launch and ground-breaking coverage.",
    "cover": "/portfolio/azam-s-staff-housing-project-2025/55151919389.jpg",
    "photos": [
      {
        "id": "55151919389",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151919389.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152062080",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152062080.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152062085",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152062085.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151918709",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151918709.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152062095",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152062095.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151685466",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151685466.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151685506",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151685506.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150791662",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55150791662.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152062280",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152062280.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152062300",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152062300.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152063205",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152063205.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151847973",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151847973.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151847933",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151847933.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151920134",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151920134.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151686631",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151686631.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151848248",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151848248.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55152063580",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152063580.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151920414",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151920414.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151687021",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151687021.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151920419",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151920419.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55150791602",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55150791602.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151685456",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151685456.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151848328",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151848328.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152063770",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55152063770.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151685546",
        "src": "/portfolio/azam-s-staff-housing-project-2025/55151685546.jpg",
        "width": 683,
        "height": 1024
      }
    ]
  },
  {
    "id": "72177720332564387",
    "title": "IAOM MEA 2025 Day 3",
    "slug": "iaom-mea-2025-day-3",
    "description": "Closing day of the IAOM Middle East & Africa conference.",
    "cover": "/portfolio/iaom-mea-2025-day-3/55151890444.jpg",
    "photos": [
      {
        "id": "55151890444",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890444.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151890454",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890454.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150763432",
        "src": "/portfolio/iaom-mea-2025-day-3/55150763432.jpg",
        "width": 1024,
        "height": 819
      },
      {
        "id": "55151890419",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890419.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151818428",
        "src": "/portfolio/iaom-mea-2025-day-3/55151818428.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150763667",
        "src": "/portfolio/iaom-mea-2025-day-3/55150763667.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151890604",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890604.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150763717",
        "src": "/portfolio/iaom-mea-2025-day-3/55150763717.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152033705",
        "src": "/portfolio/iaom-mea-2025-day-3/55152033705.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151890769",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890769.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151818638",
        "src": "/portfolio/iaom-mea-2025-day-3/55151818638.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151657306",
        "src": "/portfolio/iaom-mea-2025-day-3/55151657306.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55151890929",
        "src": "/portfolio/iaom-mea-2025-day-3/55151890929.jpg",
        "width": 1024,
        "height": 819
      },
      {
        "id": "55152033860",
        "src": "/portfolio/iaom-mea-2025-day-3/55152033860.jpg",
        "width": 1024,
        "height": 745
      },
      {
        "id": "55151657556",
        "src": "/portfolio/iaom-mea-2025-day-3/55151657556.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151657526",
        "src": "/portfolio/iaom-mea-2025-day-3/55151657526.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151657696",
        "src": "/portfolio/iaom-mea-2025-day-3/55151657696.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150764307",
        "src": "/portfolio/iaom-mea-2025-day-3/55150764307.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150764292",
        "src": "/portfolio/iaom-mea-2025-day-3/55150764292.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151819693",
        "src": "/portfolio/iaom-mea-2025-day-3/55151819693.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151658006",
        "src": "/portfolio/iaom-mea-2025-day-3/55151658006.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151891394",
        "src": "/portfolio/iaom-mea-2025-day-3/55151891394.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151819403",
        "src": "/portfolio/iaom-mea-2025-day-3/55151819403.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151658231",
        "src": "/portfolio/iaom-mea-2025-day-3/55151658231.jpg",
        "width": 1600,
        "height": 1066
      }
    ]
  },
  {
    "id": "72177720332591619",
    "title": "IAOM MEA 2025 Day 2",
    "slug": "iaom-mea-2025-day-2",
    "description": "Day two of sessions, networking and exhibition floor.",
    "cover": "/portfolio/iaom-mea-2025-day-2/55151803273.jpg",
    "photos": [
      {
        "id": "55151803273",
        "src": "/portfolio/iaom-mea-2025-day-2/55151803273.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55151638876",
        "src": "/portfolio/iaom-mea-2025-day-2/55151638876.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151872109",
        "src": "/portfolio/iaom-mea-2025-day-2/55151872109.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151872129",
        "src": "/portfolio/iaom-mea-2025-day-2/55151872129.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55152021640",
        "src": "/portfolio/iaom-mea-2025-day-2/55152021640.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151872294",
        "src": "/portfolio/iaom-mea-2025-day-2/55151872294.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55151800458",
        "src": "/portfolio/iaom-mea-2025-day-2/55151800458.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55150745997",
        "src": "/portfolio/iaom-mea-2025-day-2/55150745997.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152016040",
        "src": "/portfolio/iaom-mea-2025-day-2/55152016040.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55152016280",
        "src": "/portfolio/iaom-mea-2025-day-2/55152016280.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151639491",
        "src": "/portfolio/iaom-mea-2025-day-2/55151639491.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151873109",
        "src": "/portfolio/iaom-mea-2025-day-2/55151873109.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151800993",
        "src": "/portfolio/iaom-mea-2025-day-2/55151800993.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151801083",
        "src": "/portfolio/iaom-mea-2025-day-2/55151801083.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55151801358",
        "src": "/portfolio/iaom-mea-2025-day-2/55151801358.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150747057",
        "src": "/portfolio/iaom-mea-2025-day-2/55150747057.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151801738",
        "src": "/portfolio/iaom-mea-2025-day-2/55151801738.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151873599",
        "src": "/portfolio/iaom-mea-2025-day-2/55151873599.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151801903",
        "src": "/portfolio/iaom-mea-2025-day-2/55151801903.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151640871",
        "src": "/portfolio/iaom-mea-2025-day-2/55151640871.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150747552",
        "src": "/portfolio/iaom-mea-2025-day-2/55150747552.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55152017605",
        "src": "/portfolio/iaom-mea-2025-day-2/55152017605.jpg",
        "width": 768,
        "height": 1024
      },
      {
        "id": "55151802348",
        "src": "/portfolio/iaom-mea-2025-day-2/55151802348.jpg",
        "width": 1024,
        "height": 768
      },
      {
        "id": "55151802663",
        "src": "/portfolio/iaom-mea-2025-day-2/55151802663.jpg",
        "width": 768,
        "height": 1024
      }
    ]
  },
  {
    "id": "72177720332591124",
    "title": "IAOM MEA 2025 Day 1",
    "slug": "iaom-mea-2025-day-1",
    "description": "Opening day of the IAOM Middle East & Africa conference.",
    "cover": "/portfolio/iaom-mea-2025-day-1/55151572006.jpg",
    "photos": [
      {
        "id": "55151572006",
        "src": "/portfolio/iaom-mea-2025-day-1/55151572006.jpg",
        "width": 819,
        "height": 1024
      },
      {
        "id": "55151805584",
        "src": "/portfolio/iaom-mea-2025-day-1/55151805584.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151733568",
        "src": "/portfolio/iaom-mea-2025-day-1/55151733568.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151949465",
        "src": "/portfolio/iaom-mea-2025-day-1/55151949465.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151949405",
        "src": "/portfolio/iaom-mea-2025-day-1/55151949405.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151571931",
        "src": "/portfolio/iaom-mea-2025-day-1/55151571931.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151733748",
        "src": "/portfolio/iaom-mea-2025-day-1/55151733748.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151805854",
        "src": "/portfolio/iaom-mea-2025-day-1/55151805854.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151949680",
        "src": "/portfolio/iaom-mea-2025-day-1/55151949680.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151805989",
        "src": "/portfolio/iaom-mea-2025-day-1/55151805989.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151806109",
        "src": "/portfolio/iaom-mea-2025-day-1/55151806109.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151734033",
        "src": "/portfolio/iaom-mea-2025-day-1/55151734033.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151806089",
        "src": "/portfolio/iaom-mea-2025-day-1/55151806089.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150679102",
        "src": "/portfolio/iaom-mea-2025-day-1/55150679102.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151806459",
        "src": "/portfolio/iaom-mea-2025-day-1/55151806459.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55150679527",
        "src": "/portfolio/iaom-mea-2025-day-1/55150679527.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55150679492",
        "src": "/portfolio/iaom-mea-2025-day-1/55150679492.jpg",
        "width": 683,
        "height": 1024
      },
      {
        "id": "55150679562",
        "src": "/portfolio/iaom-mea-2025-day-1/55150679562.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151950635",
        "src": "/portfolio/iaom-mea-2025-day-1/55151950635.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151734823",
        "src": "/portfolio/iaom-mea-2025-day-1/55151734823.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55150679867",
        "src": "/portfolio/iaom-mea-2025-day-1/55150679867.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151806824",
        "src": "/portfolio/iaom-mea-2025-day-1/55151806824.jpg",
        "width": 1600,
        "height": 1066
      },
      {
        "id": "55151573336",
        "src": "/portfolio/iaom-mea-2025-day-1/55151573336.jpg",
        "width": 1024,
        "height": 683
      },
      {
        "id": "55151807204",
        "src": "/portfolio/iaom-mea-2025-day-1/55151807204.jpg",
        "width": 683,
        "height": 1024
      }
    ]
  }
];

export const allPhotos: (PortfolioPhoto & { album: string; albumSlug: string })[] = albums.flatMap((a) =>
  a.photos.map((p) => ({ ...p, album: a.title, albumSlug: a.slug }))
);
