export const services = [
  {
    title: "Conferences & Summits",
    description: "Multi-day coverage of plenary sessions, panels, side events and the exhibition floor — delivered as edited galleries within 48 hours.",
    icon: "01",
  },
  {
    title: "Corporate Events",
    description: "Launches, ground-breakings, recognition days and partner appreciation events shot with editorial sensibility for brand-ready use.",
    icon: "02",
  },
  {
    title: "Galas & Dinners",
    description: "Awards nights, fundraisers and formal dinners — the room, the speeches, the candid in-betweens — captured discreetly.",
    icon: "03",
  },
  {
    title: "Trainings & Workshops",
    description: "Workshops, classroom sessions and team off-sites documented for internal comms, social and post-event reporting.",
    icon: "04",
  },
];

export const stats = [
  { value: "10+", label: "Years behind the lens" },
  { value: "200+", label: "Events documented" },
  { value: "50,000+", label: "Frames delivered" },
  { value: "48hr", label: "Standard turnaround" },
];

// Portfolio data lives in portfolio-data.ts (generated by scripts/fetch-flickr.mjs).
export { albums, allPhotos } from "./portfolio-data";
