import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Camera, Gem, Printer, ShieldCheck } from "lucide-react";
import { portfolio, services } from "@/lib/site-data";

export default function Home() {
  return <>
    <section className="relative min-h-[92vh] overflow-hidden pt-20"><Image src="https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=2000&q=90" alt="Elegant wedding photography in Kigali" fill priority className="object-cover object-center" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(5,5,4,.94)_5%,rgba(5,5,4,.65)_48%,rgba(5,5,4,.28)_100%)]" /><div className="container-shell relative flex min-h-[calc(92vh-5rem)] items-center py-20"><div className="reveal max-w-3xl"><p className="eyebrow">Photography · Printing · Framing</p><h1 className="display mt-5 text-6xl leading-[.92] sm:text-7xl lg:text-[7rem]">Moments become<br/><em className="font-normal text-gold-light">legacy.</em></h1><p className="mt-7 max-w-xl text-base leading-8 text-stone-300 sm:text-lg">We photograph what matters, print it with precision, and finish it to live beautifully in your world.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="gold-button" href="/booking">Book your session <ArrowRight className="size-4"/></Link><Link className="ghost-button" href="/portfolio">View our work</Link></div></div></div><div className="absolute bottom-0 right-0 hidden border-l border-t hairline bg-black/45 px-10 py-6 backdrop-blur md:block"><p className="text-xs uppercase tracking-[.16em] text-stone-400">Based in</p><p className="display text-2xl">Remera, Kigali</p></div></section>
    <section className="border-y hairline py-8"><div className="container-shell grid grid-cols-2 gap-5 md:grid-cols-4">{[[Camera,"Professional studio"],[Printer,"Archival printing"],[Gem,"Custom finishing"],[ShieldCheck,"Private storage"]].map(([Icon,label])=>{const I=Icon as typeof Camera;return <div key={String(label)} className="flex items-center gap-3 text-xs uppercase tracking-wider text-stone-400"><I className="size-4 text-gold"/>{String(label)}</div>})}</div></section>
    <section className="py-24 lg:py-32"><div className="container-shell"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">What we create</p><h2 className="display mt-4 text-5xl leading-none sm:text-6xl">Everything your image deserves.</h2><p className="mt-6 max-w-md leading-7 text-stone-400">One experienced team from shutter click to the final frame. Less coordination, more craft.</p></div><div className="grid sm:grid-cols-2">{services.map(s=><article key={s.title} className="group border-b border-l hairline p-7 transition hover:bg-white/[.025]"><span className="font-mono text-xs text-gold">{s.icon}</span><h3 className="display mt-10 text-3xl">{s.title}</h3><p className="mt-3 text-sm leading-7 text-stone-400">{s.description}</p><Link href="/services" className="mt-6 inline-flex items-center gap-2 text-xs uppercase tracking-wider text-gold-light">Discover <ArrowRight className="size-3 transition group-hover:translate-x-1"/></Link></article>)}</div></div></div></section>
    <section className="bg-[#0d0d0b] py-24"><div className="container-shell"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="eyebrow">Selected stories</p><h2 className="display mt-4 text-5xl sm:text-6xl">Through our eyes.</h2></div><Link href="/portfolio" className="ghost-button">Full portfolio <ArrowRight className="size-4"/></Link></div><div className="mt-12 grid auto-rows-[260px] gap-3 md:grid-cols-3">{portfolio.slice(0,5).map((item,index)=><Link href="/portfolio" key={item.src} className={`group relative overflow-hidden ${index===0?"md:col-span-2 md:row-span-2":""}`}><Image src={item.src} fill alt={`${item.category}: ${item.title}`} className="object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-70"/><div className="absolute bottom-0 p-6"><p className="eyebrow">{item.category}</p><h3 className="display text-2xl">{item.title}</h3></div></Link>)}</div></div></section>
    <section id="about" className="py-24 lg:py-32"><div className="container-shell grid items-center gap-14 lg:grid-cols-2"><div className="relative min-h-[560px]"><Image src="https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=1200&q=85" alt="Eye in Studio photographer at work" fill className="object-cover"/><div className="absolute -bottom-6 -right-3 border border-gold bg-[#090908] p-7 sm:right-8"><strong className="display block text-5xl text-gold-light">10+</strong><span className="text-xs uppercase tracking-wider text-stone-400">Years of craft</span></div></div><div><p className="eyebrow">The studio</p><h2 className="display mt-4 text-5xl leading-none sm:text-6xl">Made with patience.<br/>Remembered forever.</h2><p className="mt-7 leading-8 text-stone-400">Eye in Studio is a full-service creative studio in Remera. Our photographers, editors and print specialists bring a thoughtful, exacting eye to every portrait, celebration and physical print.</p><p className="mt-4 leading-8 text-stone-400">We believe the best images feel honest—and the best service feels effortless.</p><Link href="/booking" className="gold-button mt-8">Create with us <ArrowRight className="size-4"/></Link></div></div></section>
    <section className="border-y hairline bg-gold py-16 text-[#0a0907]"><div className="container-shell flex flex-col items-center justify-between gap-7 text-center md:flex-row md:text-left"><div><p className="text-xs font-bold uppercase tracking-[.2em]">Your story starts here</p><h2 className="display mt-2 text-4xl sm:text-5xl">Let’s make something worth keeping.</h2></div><Link href="/booking" className="inline-flex min-h-12 items-center gap-2 bg-[#0a0907] px-7 text-xs font-bold uppercase tracking-wider text-white">Check availability <ArrowRight className="size-4"/></Link></div></section>
  </>;
}
